React summit
RWUBAKWANAYO/Javascript-Capstone-Project pull request #1
Opened 2022-04-13 21:15 UTC by RWUBAKWANAYO

# In this project we:

- configure linter to the project
- Add the index.html, and about.html files to the project
- Add google fonts and fontawesome CDN to the project
- Add fonts, colors, background to the files
- Add responsiveness of the website start with mobile-first
- Add javascript file and activate toggle on the menu-bar with js
- replace Html static data with dynamic javascript array data
- Add a popup to the speakers for more description
- fix linter error
- deploy web to the Github page

2022-04-14 01:08 UTC, codepantha requested changes
Hi @RWUBAKWANAYO 👋, 

## STATUS: REQUESTED CHANGES ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/xTiN0DvoDyWQey2B8I/giphy.gif"/>

### To Highlight 💡 
- Beautiful UI ✅ 
- Descriptive PR ✅ 
- Professional README ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-14 01:08 UTC, codepantha commented on index.html
> +			</div>
- [ ] Let's ensure to use semantic HTML tags. For instance, instead of this `<div class="hero-section">` we should have a `<section class="hero-section">`. 2 reasons I can think of for this are: to make our code clearer and more maintainable, and also to help our site be more accessible. 😎

2022-04-14 01:08 UTC, codepantha commented on index.html
> +		</div>
- [ ] Let's ensure to use semantic HTML tags. Please change `<div class="program-section">` to `<section class="program-section">`. Reference my reasons for this above ☝️

2022-04-14 01:08 UTC, codepantha commented on index.html
> +				<button type="button" class="speaker-scroll-button" id="showMore">
- [ ] Please use semantic HTML for this section 🙏

2022-04-14 01:08 UTC, codepantha commented on index.html
> +		</div>
- [ ] Please use semantic HTML for this section

2022-04-14 01:08 UTC, codepantha commented on script.js
> +    div.innerHTML = ` <div class="speaker-image-cont">
- [ ] Please use sematic HTML. use an `<article>` tag instead of `const div = document.createElement('div');` as it is the most appropriate tag for the `speaker-card`. 👍

2022-04-14 01:08 UTC, codepantha commented on index.html
> +			</header>
- [ ] While you've done a good job with the navigation, the dark bar is not present. Please take a look at the images shown below and implement it 👇 
#### Your Design
![image](https://user-images.githubusercontent.com/46839548/163293658-ea0abdca-89b9-4129-b1a3-d64d307f7aec.png)
#### Behance Design
![image](https://user-images.githubusercontent.com/46839548/163293778-938f0b9c-c40d-4ff6-903d-1a4bcb983954.png)

2022-04-14 12:44 UTC, RWUBAKWANAYO commented
# Project changes after review made by @codepantha 

- Replace all div tags with section tags at the section containers
- Replace div tag with article at the js file when we're creating new element to the HTML body with DOM
- Add dark social media container at the top of the page
- fix logic error at the menu of the project

2022-04-14 13:14 UTC, ShoiraTa commented
### **STATUS: APPROVED  ✔️** 
------
Hi @RWUBAKWANAYO,  

Your project is complete! Great job for nailing it right on the first attempt 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

![giphy](https://user-images.githubusercontent.com/77038610/154916093-53a75ff8-ba21-44ad-a25e-bdea6200d8f1.gif)

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-15 15:12 UTC, merged

2022-04-15 15:12 UTC, RWUBAKWANAYO commented
merge changes from the React-summit branch to the main branch